package com.jetsynthesys.rightlife.ui.utility

object AnalyticsParam {
    const val USER_ID = "user_id"
    const val USER_TYPE = "user_type"
    const val GENDER = "gender"
    const val AGE = "age"
    const val GOAL = "goal"
    const val SUB_GOAL = "subgoal"
    const val USER_PLAN = "user_plan"
    const val TIMESTAMP = "timestamp"
    const val TIME_TO_COMPLETE = "time_to_complete"
    const val PROFILE_SKIPPED = "profile_skipped"
    const val CHECKLIST_COMPLETE = "checklist_complete"
    const val RATING = "rating"
    const val START_TIME = "start_time"
    const val END_TIME = "end_time"
    const val TOTAL_DURATION = "total_duration"
    const val ARTICLE_ID = "article_id"
    const val VIDEO_ID = "video_id"
    const val WATCH_DURATION_PERCENT = "watch_duration_percent"
    const val AUDIO_ID = "audio_id"
    const val PRODUCT_ID = "product_id"
    const val JOURNAL_TYPE = "journal_type"
    const val JOURNAL_ID = "journal_id"
    const val AFFIRMATION_ID = "affirmation_id"
    const val AFFIRMATION_TYPE = "affrimation_type"
    const val AFFIRMATION_PLAYLIST_ID = "affirmation_playlist_id"
    const val BREATHING_TYPE_ID = "breating_type_id"
    const val BREATHING_TYPE_NAME = "breating_type_name"
    const val BREATHING_SESSION_DURATION = "breathing_session_duration"
    const val SLEEP_DURATION = "sleep_duration"
    const val DATA_EXPORT_REQUESTED = "data_export_requested"
    const val ACCOUNT_DELETED = "account_deleted"
    const val USER_SIGN_OUT = "user_signout"
}
